server:
  port: 9002

spring:
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
  datasource:
    url: jdbc:postgresql://localhost:5432/drivers
    username: postgres
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  kafka:
    consumer:
      group-id:
        ride: ride-creation-group
        status: change-status-group
        rating: update-driver-rating-group
    bootstrap-servers: localhost:9092
topic:
  name:
    ride: new-ride
    driver: available-driver
    status: change-driver-status
    rating: update-driver-rating
