server:
  port: 9003

spring:
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/v.1.0/db.changelog-v.1.0.xml
  datasource:
    url: jdbc:postgresql://localhost:5432/rides_service
    username: postgres
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
