server:
  port: 9001

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/passengers?createDatabaseIfNotExist=true
    username: postgres
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
